stages:
  - build
  - test
  - deploy

services:
  - name: docker:dind
    command: [ "--tls=false" ]

variables:
  DOCKER_HOST: "tcp://docker:2375"  # Use the correct Docker host
  DOCKER_TLS_CERTDIR: ""  # Disable TLS for Docker-in-Docker
  DOCKER_DRIVER: overlay2
  TESTCONTAINERS_RYUK_DISABLED: "true"  # 🚀 Disables Ryuk to prevent connection issues
  TESTCONTAINERS_CHECKS_DISABLE: "true"  # 🚀 Speeds up Testcontainers startup
  TESTCONTAINERS_HOST_OVERRIDE: "tcp://localhost:2375"  # Ensures correct Docker networking
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress

image: maven:3-eclipse-temurin-17

cache:
  paths:
    - .m2/repository


before_script:
  - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
  - ls -lah .secure_files
  - export GOOGLE_APPLICATION_CREDENTIALS=".secure-files/carpool-app-creds.json"

build:
  stage: build
  script:
    - mvn clean package
  only:
    - main

test:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  only:
    - main
    - merge_requests

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
  only:
    - main