image: maven:3.9.5-eclipse-temurin-17  # Use Maven with JDK 17

services:
  - docker:dind

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository" # Cache dependencies
  CACHE_DIR: ".m2/repository" # Define cache directory

cache:
  key: ${CI_COMMIT_REF_SLUG} # Cache per branch
  paths:
    - ${CACHE_DIR}

before_script:
  - echo "Using Java version:"
  - java -version
  - echo "Using Maven version:"
  - mvn -version

build:
  tags:
    - testing
  stage: build
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/  # Save compiled code

test:
  stage: test
  tags:
    - testing
  script:
    - mvn test
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml # Store JUnit test results
    paths:
      - target/site/jacoco/ # Save JaCoCo coverage reports (optional)
