spring.application.name=carpool

# Database configuration
spring.datasource.url=jdbc:postgresql://${SQL_HOST:localhost}:5432/${SQL_DB:carpool}
spring.datasource.username=${SQL_USER}
spring.datasource.password=${SQL_PASSWORD}

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

api.version=${API_VERSION:1.0}

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/${FIREBASE_PROJECT_ID}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com