spring.application.name=carpool

# Database configuration
spring.datasource.url=jdbc:postgresql://${SQL_HOST:localhost}:5432/carpool
spring.datasource.username=${SQL_USER}
spring.datasource.password=${SQL_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.version=${API_VERSION}

security.jwt.secret=${JWT_SECRET:secret}