spring.application.name=carpool

# Database configuration
spring.datasource.url=jdbc:postgresql://${SQL_HOST:localhost}:5432/carpool
spring.datasource.username=${SQL_USER}
spring.datasource.password=${SQL_PASSWORD}

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Spring SQL init scripts
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:sql/init-h2gis.sql

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

api.version=${API_VERSION}

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/${FIREBASE_PROJECT_ID}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com